import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

class ConnectedScreen extends StatefulWidget {
  const ConnectedScreen({super.key, required this.data});
    final Map<String, dynamic> data;

      @override
        State<ConnectedScreen> createState() => _ConnectedScreenState();
        }

        class _ConnectedScreenState extends State<ConnectedScreen> {
          final String _uid = FirebaseAuth.instance.currentUser!.uid;
            StreamSubscription<Position>? _sub;
              Timer? _timer;
                Position? _last;
                  bool _sharing = false;
                    String? _message;

                      DocumentReference<Map<String, dynamic>> get _locRef =>
                            FirebaseFirestore.instance.collection('locations').doc(_uid);

                              void _write(Position p) {
                                  _last = p;
                                      _locRef.set({
                                            'lat': p.latitude,
                                                  'lng': p.longitude,
                                                        'accuracy': p.accuracy,
                                                              'updatedAt': FieldValue.serverTimestamp(),
                                                                  }).catchError((_) {});
                                                                    }

                                                                      Future<void> _start() async {
                                                                          setState(() => _message = null);
                                                                              if (!await Geolocator.isLocationServiceEnabled()) {
                                                                                    setState(() => _message = 'Phone-এর Location (GPS) চালু করুন');
                                                                                          return;
                                                                                              }
                                                                                                  var perm = await Geolocator.checkPermission();
                                                                                                      if (perm == LocationPermission.denied) {
                                                                                                            perm = await Geolocator.requestPermission();
                                                                                                                }
                                                                                                                    if (perm == LocationPermission.denied ||
                                                                                                                            perm == LocationPermission.deniedForever) {
                                                                                                                                  setState(() => _message = 'Location permission দেওয়া হয়নি');
                                                                                                                                        return;
                                                                                                                                            }
                                                                                                                                                _sub = Geolocator.getPositionStream(
                                                                                                                                                      locationSettings: const LocationSettings(
                                                                                                                                                              accuracy: LocationAccuracy.high,
                                                                                                                                                                      distanceFilter: 25,
                                                                                                                                                                            ),
                                                                                                                                                                                ).listen(_write, onError: (_) {});
                                                                                                                                                                                    _timer = Timer.periodic(const Duration(seconds: 60), (_) {
                                                                                                                                                                                          final p = _last;
                                                                                                                                                                                                if (p != null) _write(p);
                                                                                                                                                                                                    });
                                                                                                                                                                                                        setState(() => _sharing = true);
                                                                                                                                                                                                          }

                                                                                                                                                                                                            Future<void> _stop() async {
                                                                                                                                                                                                                await _sub?.cancel();
                                                                                                                                                                                                                    _timer?.cancel();
                                                                                                                                                                                                                        _sub = null;
                                                                                                                                                                                                                            _timer = null;
                                                                                                                                                                                                                                _last = null;
                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                          await _locRef.delete();
                                                                                                                                                                                                                                              } catch (_) {}
                                                                                                                                                                                                                                                  if (mounted) setState(() => _sharing = false);
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                      Future<void> _disconnect() async {
                                                                                                                                                                                                                                                          await _stop();
                                                                                                                                                                                                                                                              await FirebaseFirestore.instance.collection('children').doc(_uid).delete();
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                  @override
                                                                                                                                                                                                                                                                    void dispose() {
                                                                                                                                                                                                                                                                        _sub?.cancel();
                                                                                                                                                                                                                                                                            _timer?.cancel();
                                                                                                                                                                                                                                                                                super.dispose();
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                    @override
                                                                                                                                                                                                                                                                                      Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                          final name = widget.data['childName'] ?? '';
                                                                                                                                                                                                                                                                                              return Scaffold(
                                                                                                                                                                                                                                                                                                    appBar: AppBar(title: const Text('Child App')),
                                                                                                                                                                                                                                                                                                          body: ListView(
                                                                                                                                                                                                                                                                                                                  padding: const EdgeInsets.all(24),
                                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                                    const Icon(Icons.link, size: 64, color: Colors.green),
                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                        Center(
                                                                                                                                                                                                                                                                                                                                                                      child: Text('Parent-এর সাথে যুক্ত ✅',
                                                                                                                                                                                                                                                                                                                                                                                        style: Theme.of(context).textTheme.titleLarge)),
                                                                                                                                                                                                                                                                                                                                                                                                  Center(child: Text('নাম: $name')),
                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 24),
                                                                                                                                                                                                                                                                                                                                                                                                                      Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                  child: SwitchListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                title: const Text('Location শেয়ার করুন'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                              subtitle: Text(_sharing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? '🟢 ON: Parent আপনার location দেখতে পাচ্ছে'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : '🔴 OFF: কেউ আপনার location দেখতে পাচ্ছে না'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value: _sharing,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChanged: (v) => v ? _start() : _stop(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (_message != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: const EdgeInsets.only(top: 8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: Text(_message!, style: const TextStyle(color: Colors.red)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 32),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      OutlinedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPressed: _disconnect, child: const Text('Disconnect')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }