import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:shared_preferences/shared_preferences.dart';

class ConnectedScreen extends StatefulWidget {
  const ConnectedScreen({super.key, required this.data});
    final Map<String, dynamic> data;

      @override
        State<ConnectedScreen> createState() => _ConnectedScreenState();
        }

        class _ConnectedScreenState extends State<ConnectedScreen> {
          static const _prefKey = 'sharing_for_code';
            final String _uid = FirebaseAuth.instance.currentUser!.uid;
              StreamSubscription<Position>? _sub;
                bool _sharing = false;
                  String? _message;

                    String get _code => (widget.data['code'] ?? '').toString();

                      DocumentReference<Map<String, dynamic>> get _locRef =>
                            FirebaseFirestore.instance.collection('locations').doc(_uid);

                              @override
                                void initState() {
                                    super.initState();
                                        _restore();
                                          }

                                            // আগে ON থাকলে এবং একই pairing হলে নিজে থেকে চালু হবে
                                              Future<void> _restore() async {
                                                  final prefs = await SharedPreferences.getInstance();
                                                      if (prefs.getString(_prefKey) == _code) {
                                                            await _start(auto: true);
                                                                }
                                                                  }

                                                                    Future<bool> _ensurePermissions({required bool ask}) async {
                                                                        if (!await Geolocator.isLocationServiceEnabled()) {
                                                                              _message = 'Phone-এর Location (GPS) চালু করুন';
                                                                                    return false;
                                                                                        }
                                                                                            var perm = await Geolocator.checkPermission();
                                                                                                if (perm == LocationPermission.denied && ask) {
                                                                                                      perm = await Geolocator.requestPermission();
                                                                                                          }
                                                                                                              if (perm == LocationPermission.denied ||
                                                                                                                      perm == LocationPermission.deniedForever) {
                                                                                                                            _message =
                                                                                                                                      'Location permission দেওয়া হয়নি। Settings → Apps → Child App → Permissions → Location → "While using the app" দিন';
                                                                                                                                            return false;
                                                                                                                                                }
                                                                                                                                                    var notif = await Permission.notification.status;
                                                                                                                                                        if (!notif.isGranted && ask) {
                                                                                                                                                              notif = await Permission.notification.request();
                                                                                                                                                                  }
                                                                                                                                                                      if (!notif.isGranted) {
                                                                                                                                                                            _message =
                                                                                                                                                                                      'Notification permission ছাড়া sharing চালু হবে না, কারণ sharing চললে notification-এ দেখানো বাধ্যতামূলক';
                                                                                                                                                                                            return false;
                                                                                                                                                                                                }
                                                                                                                                                                                                    return true;
                                                                                                                                                                                                      }

                                                                                                                                                                                                        Future<void> _start({bool auto = false}) async {
                                                                                                                                                                                                            if (_sub != null) return;
                                                                                                                                                                                                                _message = null;
                                                                                                                                                                                                                    final ok = await _ensurePermissions(ask: !auto);
                                                                                                                                                                                                                        if (!ok) {
                                                                                                                                                                                                                              if (auto) await _stop();
                                                                                                                                                                                                                                    if (mounted) setState(() {});
                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                  final settings = AndroidSettings(
                                                                                                                                                                                                                                                        accuracy: LocationAccuracy.high,
                                                                                                                                                                                                                                                              distanceFilter: 0,
                                                                                                                                                                                                                                                                    intervalDuration: const Duration(seconds: 60),
                                                                                                                                                                                                                                                                          foregroundNotificationConfig: ForegroundNotificationConfig(
                                                                                                                                                                                                                                                                                  notificationTitle: 'Location sharing চালু আছে',
                                                                                                                                                                                                                                                                                          notificationText:
                                                                                                                                                                                                                                                                                                      'Parent আপনার location দেখতে পাচ্ছেন। বন্ধ করতে app খুলুন।',
                                                                                                                                                                                                                                                                                                              notificationChannelName: 'Location sharing',
                                                                                                                                                                                                                                                                                                                      enableWakeLock: true,
                                                                                                                                                                                                                                                                                                                              setOngoing: true,
                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                            _sub = Geolocator.getPositionStream(locationSettings: settings)
                                                                                                                                                                                                                                                                                                                                                    .listen(_write, onError: (_) {});
                                                                                                                                                                                                                                                                                                                                                        final prefs = await SharedPreferences.getInstance();
                                                                                                                                                                                                                                                                                                                                                            await prefs.setString(_prefKey, _code);
                                                                                                                                                                                                                                                                                                                                                                if (mounted) setState(() => _sharing = true);
                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                    void _write(Position p) {
                                                                                                                                                                                                                                                                                                                                                                        _locRef.set({
                                                                                                                                                                                                                                                                                                                                                                              'sharing': true,
                                                                                                                                                                                                                                                                                                                                                                                    'lat': p.latitude,
                                                                                                                                                                                                                                                                                                                                                                                          'lng': p.longitude,
                                                                                                                                                                                                                                                                                                                                                                                                'accuracy': p.accuracy,
                                                                                                                                                                                                                                                                                                                                                                                                      'updatedAt': FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                          }).catchError((_) {});
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                              Future<void> _stop() async {
                                                                                                                                                                                                                                                                                                                                                                                                                  await _sub?.cancel();
                                                                                                                                                                                                                                                                                                                                                                                                                      _sub = null;
                                                                                                                                                                                                                                                                                                                                                                                                                          final prefs = await SharedPreferences.getInstance();
                                                                                                                                                                                                                                                                                                                                                                                                                              await prefs.remove(_prefKey);
                                                                                                                                                                                                                                                                                                                                                                                                                                  // location মুছে যায়, শুধু "বন্ধ করেছে" আর সময় থাকে
                                                                                                                                                                                                                                                                                                                                                                                                                                      _locRef.set({
                                                                                                                                                                                                                                                                                                                                                                                                                                            'sharing': false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  'stoppedAt': FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }).catchError((_) {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (mounted) setState(() => _sharing = false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                              Future<void> _onToggle(bool on) async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!on) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await _stop();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      final agreed = await showDialog<bool>(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            context: context,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  builder: (ctx) => AlertDialog(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title: const Text('Location শেয়ার করবেন?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  content: const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'চালু করলে Parent আপনার phone-এর অবস্থান দেখতে পারবেন, app খোলা না থাকলেও। চালু থাকলে notification-এ সবসময় দেখা যাবে। আপনি যেকোনো সময় এখান থেকে বন্ধ করতে পারবেন।'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      actions: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TextButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onPressed: () => Navigator.pop(ctx, false),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: const Text('না')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      FilledButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPressed: () => Navigator.pop(ctx, true),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: const Text('রাজি আছি')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (agreed == true) await _start();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Future<void> _disconnect() async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await _sub?.cancel();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _sub = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        final prefs = await SharedPreferences.getInstance();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await prefs.remove(_prefKey);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _locRef.delete().catchError((_) {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FirebaseFirestore.instance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .collection('children')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .doc(_uid)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .delete()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .catchError((_) {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          void dispose() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _sub?.cancel();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  super.dispose();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            final name = widget.data['childName'] ?? '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      appBar: AppBar(title: const Text('Child App')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            body: ListView(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: const EdgeInsets.all(24),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const Icon(Icons.link, size: 64, color: Colors.green),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Center(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: Text('Parent-এর সাথে যুক্ত ✅',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: Theme.of(context).textTheme.titleLarge)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Center(child: Text('নাম: $name')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 24),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: SwitchListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  title: const Text('Location শেয়ার করুন'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                subtitle: Text(_sharing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? '🟢 ON: Parent আপনার location দেখতে পাচ্ছেন'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : '🔴 OFF: কেউ আপনার location দেখতে পাচ্ছে না'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value: _sharing,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChanged: _onToggle,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (_message != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: const EdgeInsets.only(top: 8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: Text(_message!, style: const TextStyle(color: Colors.red)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  leading: const Icon(Icons.battery_alert),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: const Text('Battery সেটিং'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              subtitle: const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Background-এ চালু রাখতে Battery → "Unrestricted" দিন'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onTap: openAppSettings,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 32),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        OutlinedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: _disconnect, child: const Text('Disconnect')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          