import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_foreground_task/flutter_foreground_task.dart';
import 'package:geolocator/geolocator.dart';

@pragma('vm:entry-point')
void startLocationService() {
  FlutterForegroundTask.setTaskHandler(LocationTaskHandler());
  }

  class LocationTaskHandler extends TaskHandler {
    StreamSubscription<Position>? _sub;
      String? _uid;

        String _hhmm(DateTime t) =>
              '${t.hour.toString().padLeft(2, '0')}:${t.minute.toString().padLeft(2, '0')}';

                Future<void> _write(Map<String, dynamic> data) async {
                    final uid = _uid;
                        if (uid == null) return;
                            try {
                                  await FirebaseFirestore.instance
                                            .collection('locations')
                                                      .doc(uid)
                                                                .set(data);
                                                                      final now = DateTime.now();
                                                                            FlutterForegroundTask.sendDataToMain(
                                                                                      {'type': 'sent', 'ms': now.millisecondsSinceEpoch});
                                                                                            if (data.containsKey('lat')) {
                                                                                                    FlutterForegroundTask.updateService(
                                                                                                              notificationText:
                                                                                                                            'Parent আপনার location দেখতে পাচ্ছেন · শেষ আপডেট ${_hhmm(now)}',
                                                                                                                                    );
                                                                                                                                          }
                                                                                                                                              } catch (e) {
                                                                                                                                                    FlutterForegroundTask.sendDataToMain(
                                                                                                                                                              {'type': 'error', 'msg': e.toString()});
                                                                                                                                                                  }
                                                                                                                                                                    }

                                                                                                                                                                      Future<void> _sendPosition(Position p) {
                                                                                                                                                                          return _write({
                                                                                                                                                                                'sharing': true,
                                                                                                                                                                                      'lat': p.latitude,
                                                                                                                                                                                            'lng': p.longitude,
                                                                                                                                                                                                  'accuracy': p.accuracy,
                                                                                                                                                                                                        'updatedAt': FieldValue.serverTimestamp(),
                                                                                                                                                                                                            });
                                                                                                                                                                                                              }

                                                                                                                                                                                                                @override
                                                                                                                                                                                                                  Future<void> onStart(DateTime timestamp, TaskStarter starter) async {
                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                            await Firebase.initializeApp();
                                                                                                                                                                                                                                } catch (_) {}

                                                                                                                                                                                                                                    final saved = await FlutterForegroundTask.getData(key: 'uid');
                                                                                                                                                                                                                                        _uid = saved?.toString();

                                                                                                                                                                                                                                            User? user;
                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                      user = await FirebaseAuth.instance
                                                                                                                                                                                                                                                                .authStateChanges()
                                                                                                                                                                                                                                                                          .first
                                                                                                                                                                                                                                                                                    .timeout(const Duration(seconds: 15));
                                                                                                                                                                                                                                                                                        } catch (_) {}

                                                                                                                                                                                                                                                                                            if (_uid == null || user == null || user.uid != _uid) {
                                                                                                                                                                                                                                                                                                  FlutterForegroundTask.sendDataToMain({
                                                                                                                                                                                                                                                                                                          'type': 'error',
                                                                                                                                                                                                                                                                                                                  'msg': 'Login তথ্য পাওয়া যায়নি, app খুলে আবার চালু করুন'
                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                      // সুইচ ON হওয়ার সাথে সাথেই parent দেখবে "চালু আছে"
                                                                                                                                                                                                                                                                                                                                          unawaited(
                                                                                                                                                                                                                                                                                                                                                  _write({'sharing': true, 'updatedAt': FieldValue.serverTimestamp()}));

                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                            final last = await Geolocator.getLastKnownPosition();
                                                                                                                                                                                                                                                                                                                                                                  if (last != null &&
                                                                                                                                                                                                                                                                                                                                                                            DateTime.now().difference(last.timestamp) <
                                                                                                                                                                                                                                                                                                                                                                                          const Duration(minutes: 10)) {
                                                                                                                                                                                                                                                                                                                                                                                                  unawaited(_sendPosition(last));
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                            } catch (_) {}

                                                                                                                                                                                                                                                                                                                                                                                                                _sub = Geolocator.getPositionStream(
                                                                                                                                                                                                                                                                                                                                                                                                                      locationSettings: AndroidSettings(
                                                                                                                                                                                                                                                                                                                                                                                                                              accuracy: LocationAccuracy.high,
                                                                                                                                                                                                                                                                                                                                                                                                                                      distanceFilter: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                              intervalDuration: const Duration(seconds: 60),
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ).listen(
                                                                                                                                                                                                                                                                                                                                                                                                                                                              (p) => unawaited(_sendPosition(p)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onError: (Object e) => FlutterForegroundTask.sendDataToMain(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {'type': 'error', 'msg': 'GPS: $e'}),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        void onRepeatEvent(DateTime timestamp) {}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Future<void> onDestroy(DateTime timestamp, bool isTimeout) async {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await _sub?.cancel();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _sub = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      