import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

class LocationPage extends StatefulWidget {
  const LocationPage(
        {super.key, required this.childId, required this.childName});
          final String childId;
            final String childName;

              @override
                State<LocationPage> createState() => _LocationPageState();
                }

                class _LocationPageState extends State<LocationPage> {
                  Timer? _tick;

                    @override
                      void initState() {
                          super.initState();
                              _tick = Timer.periodic(const Duration(seconds: 30), (_) {
                                    if (mounted) setState(() {});
                                        });
                                          }

                                            @override
                                              void dispose() {
                                                  _tick?.cancel();
                                                      super.dispose();
                                                        }

                                                          String _ago(DateTime t) {
                                                              final d = DateTime.now().difference(t);
                                                                  if (d.inSeconds < 60) return 'কয়েক সেকেন্ড আগে';
                                                                      if (d.inMinutes < 60) return '${d.inMinutes} মিনিট আগে';
                                                                          if (d.inHours < 24) return '${d.inHours} ঘণ্টা আগে';
                                                                              return '${d.inDays} দিন আগে';
                                                                                }

                                                                                  String _clock(Timestamp? t) {
                                                                                      if (t == null) return 'এইমাত্র';
                                                                                          final dt = t.toDate();
                                                                                              final time = TimeOfDay.fromDateTime(dt).format(context);
                                                                                                  final now = DateTime.now();
                                                                                                      final today =
                                                                                                              dt.year == now.year && dt.month == now.month && dt.day == now.day;
                                                                                                                  return today ? time : '${dt.day}/${dt.month} $time';
                                                                                                                    }

                                                                                                                      Widget _notice(String text) => Center(
                                                                                                                              child: Padding(
                                                                                                                                        padding: const EdgeInsets.all(24),
                                                                                                                                                  child: Text(text, textAlign: TextAlign.center),
                                                                                                                                                          ),
                                                                                                                                                                );

                                                                                                                                                                  @override
                                                                                                                                                                    Widget build(BuildContext context) {
                                                                                                                                                                        return Scaffold(
                                                                                                                                                                              appBar: AppBar(title: Text('${widget.childName}-এর Location')),
                                                                                                                                                                                    body: StreamBuilder<DocumentSnapshot<Map<String, dynamic>>>(
                                                                                                                                                                                            stream: FirebaseFirestore.instance
                                                                                                                                                                                                        .collection('locations')
                                                                                                                                                                                                                    .doc(widget.childId)
                                                                                                                                                                                                                                .snapshots(),
                                                                                                                                                                                                                                        builder: (context, snap) {
                                                                                                                                                                                                                                                  if (snap.hasError) return _notice('Error: ${snap.error}');
                                                                                                                                                                                                                                                            if (!snap.hasData) {
                                                                                                                                                                                                                                                                        return const Center(child: CircularProgressIndicator());
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                            final d = snap.data!.data();
                                                                                                                                                                                                                                                                                                      if (d == null) {
                                                                                                                                                                                                                                                                                                                  return _notice('⚪ Child এখনো location sharing চালু করেনি।');
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                      if (d['sharing'] == false) {
                                                                                                                                                                                                                                                                                                                                                  final when = _clock(d['stoppedAt'] as Timestamp?);
                                                                                                                                                                                                                                                                                                                                                              return _notice(
                                                                                                                                                                                                                                                                                                                                                                              '🔴 Child location sharing বন্ধ করেছে\n$when-এ।\n\nচালু করা বা না করা child-এর সিদ্ধান্ত।');
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                  if (d['lat'] == null || d['lng'] == null) {
                                                                                                                                                                                                                                                                                                                                                                                                              return _notice('Location এখনো আসেনি, একটু অপেক্ষা করুন।');
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                  final point = LatLng(
                                                                                                                                                                                                                                                                                                                                                                                                                                                (d['lat'] as num).toDouble(), (d['lng'] as num).toDouble());
                                                                                                                                                                                                                                                                                                                                                                                                                                                          final updated = (d['updatedAt'] as Timestamp?)?.toDate();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    final agoText = updated == null ? 'এইমাত্র' : _ago(updated);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              final age =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updated == null ? Duration.zero : DateTime.now().difference(updated);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      final stale = age > const Duration(minutes: 5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: double.infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: stale ? Colors.orange.shade100 : Colors.green.shade50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: const EdgeInsets.all(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Text(stale
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? '⚠️ শেষ আপডেট $agoText। Phone বন্ধ, internet নেই, বা child app বন্ধ করেছে হতে পারে। নিচে শেষ জানা অবস্থান।'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : '🟢 Sharing ON · সর্বশেষ আপডেট: $agoText'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Expanded(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: Stack(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FlutterMap(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          key: ValueKey(point),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                options: MapOptions(initialCenter: point, initialZoom: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              TileLayer(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        urlTemplate:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                userAgentPackageName: 'com.shahabir.pcontrol.parent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                MarkerLayer(markers: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Marker(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      point: point,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: 48,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              height: 48,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Icon(Icons.location_pin,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: stale ? Colors.orange : Colors.red,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          size: 48),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const Positioned(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                right: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      bottom: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: Text('© OpenStreetMap contributors',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: TextStyle(fontSize: 11)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }