import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

class LocationPage extends StatelessWidget {
  const LocationPage(
        {super.key, required this.childId, required this.childName});
          final String childId;
            final String childName;

              String _ago(Timestamp? t) {
                  if (t == null) return 'এইমাত্র';
                      final d = DateTime.now().difference(t.toDate());
                          if (d.inSeconds < 60) return 'কয়েক সেকেন্ড আগে';
                              if (d.inMinutes < 60) return '${d.inMinutes} মিনিট আগে';
                                  if (d.inHours < 24) return '${d.inHours} ঘণ্টা আগে';
                                      return '${d.inDays} দিন আগে';
                                        }

                                          @override
                                            Widget build(BuildContext context) {
                                                return Scaffold(
                                                      appBar: AppBar(title: Text('$childName-এর Location')),
                                                            body: StreamBuilder<DocumentSnapshot<Map<String, dynamic>>>(
                                                                    stream: FirebaseFirestore.instance
                                                                                .collection('locations')
                                                                                            .doc(childId)
                                                                                                        .snapshots(),
                                                                                                                builder: (context, snap) {
                                                                                                                          if (snap.hasError) {
                                                                                                                                      return Center(child: Text('Error: ${snap.error}'));
                                                                                                                                                }
                                                                                                                                                          if (!snap.hasData) {
                                                                                                                                                                      return const Center(child: CircularProgressIndicator());
                                                                                                                                                                                }
                                                                                                                                                                                          final d = snap.data!.data();
                                                                                                                                                                                                    if (d == null) {
                                                                                                                                                                                                                return const Center(
                                                                                                                                                                                                                              child: Padding(
                                                                                                                                                                                                                                              padding: EdgeInsets.all(24),
                                                                                                                                                                                                                                                              child: Text(
                                                                                                                                                                                                                                                                                  '🔴 Location sharing বন্ধ আছে।\nChild নিজে চালু করলে এখানে দেখা যাবে।',
                                                                                                                                                                                                                                                                                                      textAlign: TextAlign.center),
                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                    final point = LatLng(
                                                                                                                                                                                                                                                                                                                                                                  (d['lat'] as num).toDouble(), (d['lng'] as num).toDouble());
                                                                                                                                                                                                                                                                                                                                                                            final ago = _ago(d['updatedAt'] as Timestamp?);
                                                                                                                                                                                                                                                                                                                                                                                      return Column(
                                                                                                                                                                                                                                                                                                                                                                                                  children: [
                                                                                                                                                                                                                                                                                                                                                                                                                Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                width: double.infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                color: Colors.green.shade50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: const EdgeInsets.all(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: Text('🟢 Sharing ON · সর্বশেষ আপডেট: $ago'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Expanded(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: Stack(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  FlutterMap(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        key: ValueKey(point),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              options: MapOptions(initialCenter: point, initialZoom: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TileLayer(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      urlTemplate:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              userAgentPackageName: 'com.shahabir.pcontrol.parent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              MarkerLayer(markers: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Marker(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    point: point,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: 48,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            height: 48,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: const Icon(Icons.location_pin,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: Colors.red, size: 48),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const Positioned(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              right: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bottom: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Text('© OpenStreetMap contributors',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: TextStyle(fontSize: 11)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  