import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp();
      runApp(const ParentApp());
      }

      class ParentApp extends StatelessWidget {
        const ParentApp({super.key});

          @override
            Widget build(BuildContext context) {
                return MaterialApp(
                      title: 'Parent App',
                            theme: ThemeData(colorSchemeSeed: Colors.indigo, useMaterial3: true),
                                  home: StreamBuilder<User?>(
                                          stream: FirebaseAuth.instance.authStateChanges(),
                                                  builder: (context, snap) {
                                                            if (snap.connectionState == ConnectionState.waiting) {
                                                                        return const Scaffold(
                                                                                        body: Center(child: CircularProgressIndicator()));
                                                                                                  }
                                                                                                            return snap.data == null ? const AuthPage() : const HomePage();
                                                                                                                    },
                                                                                                                          ),
                                                                                                                              );
                                                                                                                                }
                                                                                                                                }

                                                                                                                                class AuthPage extends StatefulWidget {
                                                                                                                                  const AuthPage({super.key});

                                                                                                                                    @override
                                                                                                                                      State<AuthPage> createState() => _AuthPageState();
                                                                                                                                      }

                                                                                                                                      class _AuthPageState extends State<AuthPage> {
                                                                                                                                        final _email = TextEditingController();
                                                                                                                                          final _pass = TextEditingController();
                                                                                                                                            bool _register = false;
                                                                                                                                              bool _busy = false;
                                                                                                                                                String? _error;

                                                                                                                                                  Future<void> _submit() async {
                                                                                                                                                      setState(() {
                                                                                                                                                            _busy = true;
                                                                                                                                                                  _error = null;
                                                                                                                                                                      });
                                                                                                                                                                          try {
                                                                                                                                                                                final auth = FirebaseAuth.instance;
                                                                                                                                                                                      final email = _email.text.trim();
                                                                                                                                                                                            if (_register) {
                                                                                                                                                                                                    final cred = await auth.createUserWithEmailAndPassword(
                                                                                                                                                                                                                email: email, password: _pass.text);
                                                                                                                                                                                                                        await FirebaseFirestore.instance
                                                                                                                                                                                                                                    .collection('users')
                                                                                                                                                                                                                                                .doc(cred.user!.uid)
                                                                                                                                                                                                                                                            .set({
                                                                                                                                                                                                                                                                      'email': email,
                                                                                                                                                                                                                                                                                'role': 'parent',
                                                                                                                                                                                                                                                                                          'createdAt': FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                await auth.signInWithEmailAndPassword(
                                                                                                                                                                                                                                                                                                                            email: email, password: _pass.text);
                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                      } on FirebaseAuthException catch (e) {
                                                                                                                                                                                                                                                                                                                                            if (mounted) setState(() => _error = e.message);
                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                      if (mounted) setState(() => _error = e.toString());
                                                                                                                                                                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                                                                                                                                                                if (mounted) setState(() => _busy = false);
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                        @override
                                                                                                                                                                                                                                                                                                                                                                          Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                              return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                    appBar: AppBar(title: Text(_register ? 'Parent Register' : 'Parent Login')),
                                                                                                                                                                                                                                                                                                                                                                                          body: ListView(
                                                                                                                                                                                                                                                                                                                                                                                                  padding: const EdgeInsets.all(24),
                                                                                                                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                                                                                                                    TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                controller: _email,
                                                                                                                                                                                                                                                                                                                                                                                                                                            keyboardType: TextInputType.emailAddress,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        decoration: const InputDecoration(labelText: 'Email'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  controller: _pass,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              obscureText: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          decoration:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const InputDecoration(labelText: 'Password (min 6 characters)'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (_error != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: const EdgeInsets.only(bottom: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: Text(_error!, style: const TextStyle(color: Colors.red)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      FilledButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onPressed: _busy ? null : _submit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: _busy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? const SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  height: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: CircularProgressIndicator(strokeWidth: 2))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : Text(_register ? 'Register' : 'Login'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              TextButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPressed: () => setState(() => _register = !_register),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: Text(_register
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? 'Already have an account? Login'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : 'New here? Register'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class HomePage extends StatelessWidget {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const HomePage({super.key});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              final user = FirebaseAuth.instance.currentUser!;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: const Text('Parent Dashboard'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        actions: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              icon: const Icon(Icons.logout),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPressed: () => FirebaseAuth.instance.signOut(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        body: Center(child: Text('Logged in as\n${user.email}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textAlign: TextAlign.center)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }